version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: deals_postgres
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: deals_image
    container_name: deals
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
