# Generated by Django 3.2.12 on 2022-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200, verbose_name='Логин покупателя')),
                ('item', models.CharField(max_length=200, verbose_name='Наименование товара')),
                ('total', models.FloatField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TopCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Логин клиента')),
                ('spent_money', models.FloatField(verbose_name='Сумма потраченных средств')),
                ('gems', models.JSONField(verbose_name='Список камней')),
            ],
            options={
                'verbose_name': 'Топ',
                'verbose_name_plural': 'Топы',
                'ordering': ['-spent_money'],
            },
        ),
    ]
